### ISSUE TITLE
Bug: Pronoun badge shifts on Firefox 

### ISSUE THREAD

**Issue by PogSothoth** [Alejo47/chat_pronouns_browser_extension#6] opened 2021-04-16 14:25 UTC
Currently, if a user has more than one badge on Twitch and hovers over the pronoun badge, hovering over another badge will cause the pronouns to shift to the left. This appears to happen For any number of badges, but I've only been able to reproduce with 3.

![image](https://user-images.githubusercontent.com/82663941/115038330-6e267400-9e9d-11eb-82f2-3cb8fc20e388.png)

![image](https://user-images.githubusercontent.com/82663941/115038351-7383be80-9e9d-11eb-9256-9de938ba3799.png)

Firefox version is 87.0

**Comment by Alejo47** [comment] 2021-04-18 01:14
This is a known issue not to Firefox alone, this happens due to the way Twitch handles badges, when you hover over them Twitch re-renders them and in doing so it tries to place it in the same spot, however for some reason this moves them to the right of the pronouns badge if they are to the left of it.
There are ways I could potentially fix this, but this would risk breaking compatibility with other extensions like FFZ or BTTV so it requires very exhaustive testing. I will be looking into this but I cannot make any promises this will be fixed in the near future

**Comment by Alejo47** [comment] 2021-08-20 22:50
This issue has been fixed on Twitch's end and does not seem to be reproducible anymore.

**Closed as completed by Alejo47** 2021-08-20 22:50 UTC
Labels: Bug
